name: CREATING_THE_MOCK_SERVICE_WORKER

on:
  pull_request:
    branches:
      - "renovate/msw-**"
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npx msw init ./public
          git add .
          git commit -m "create service worker file"
          git push
