name: Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      # Create cache for Playwright installation
      - name: Restore Playwright Installation Cache
        id: playwright-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm.lock.yaml') }}

        # Install Playwright if pnpm.lock.yaml changed
      - name: Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install-deps chromium

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type

      - name: Unit Test
        run: pnpm test

      - name: Run E2E test
        run: pnpm e2e
